'use client';
import { useEffect, useMemo, useState } from 'react';
const steps=['اختيار المركبة','بيانات المشتري','التحقق','السعر','الدفع','مراجعة العقد','الموافقة','نقل الملكية','إتمام'];
type Vehicle={id:string;plateNumber:string;make:string;model:string;year:number;price:string};
export default function TransferPage(){
 const [current,setCurrent]=useState(0); const [vehicles,setVehicles]=useState<Vehicle[]>([]); const [vehicleId,setVehicleId]=useState(''); const [buyerId,setBuyerId]=useState(''); const [price,setPrice]=useState(''); const [sale,setSale]=useState<any>(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
 useEffect(()=>{fetch('/api/vehicles').then(r=>r.json()).then(x=>{if(x.ok)setVehicles(x.vehicles)})},[]);
 const selected=useMemo(()=>vehicles.find(v=>v.id===vehicleId),[vehicles,vehicleId]);
 async function create(){setError('');setLoading(true);try{const r=await fetch('/api/transfers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({vehicleId,buyerId,salePrice:Number(price)})});const x=await r.json();if(!r.ok)throw new Error(x.error||'فشل إنشاء العملية');setSale(x.sale);setCurrent(1)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 async function status(status:string){if(!sale)return;setLoading(true);setError('');try{const r=await fetch(`/api/transfers/${sale.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});const x=await r.json();if(!r.ok)throw new Error(x.error||'فشل تحديث العملية');setSale(x.sale);setCurrent(Math.min(current+1,steps.length-1))}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 return <div className="max-w-5xl mx-auto p-6"><h1 className="text-2xl font-bold mb-6">نقل ملكية مركبة</h1><div className="flex gap-2 overflow-x-auto pb-4">{steps.map((s,i)=><div key={i} className={`whitespace-nowrap px-4 py-2 rounded-full text-sm ${i===current?'bg-green-800 text-white':i<current?'bg-green-100 text-green-800 border border-green-300':'bg-gray-100'}`}>{i+1}. {s}</div>)}</div>
 <div className="bg-white rounded-xl p-6 border shadow-sm space-y-5"><div><label className="block mb-1 font-medium">المركبة</label><select value={vehicleId} onChange={e=>{setVehicleId(e.target.value);const v=vehicles.find(x=>x.id===e.target.value);if(v)setPrice(v.price)}} className="w-full border rounded-lg p-3"><option value="">اختر المركبة</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.make} {v.model} — {v.plateNumber}</option>)}</select></div><div><label className="block mb-1 font-medium">معرف المشتري</label><input value={buyerId} onChange={e=>setBuyerId(e.target.value)} placeholder="User ID" className="w-full border rounded-lg p-3" /></div><div><label className="block mb-1 font-medium">سعر المركبة بالريال اليمني</label><input type="number" min="1" value={price} onChange={e=>setPrice(e.target.value)} className="w-full border rounded-lg p-3" /></div>{selected&&<div className="rounded-lg bg-gray-50 p-4 text-sm">المركبة المختارة: {selected.make} {selected.model} — {selected.plateNumber}</div>}{sale&&<div className="rounded-lg bg-green-50 border border-green-200 p-4 text-sm">رقم العملية: <b>{sale.id}</b><br/>الحالة: <b>{sale.status}</b><br/>رسوم النقل: <b>80 USD</b></div>}{error&&<div className="rounded-lg bg-red-50 border border-red-200 p-3 text-red-700">{error}</div>}
 <div className="flex gap-3"><button disabled={loading||!vehicleId||!buyerId||!price} onClick={create} className="px-6 py-3 bg-green-800 text-white rounded-lg disabled:opacity-50">{loading?'جارٍ التنفيذ...':'إنشاء طلب النقل'}</button>{sale&&<button disabled={loading} onClick={()=>status('BUYER_ACCEPTED')} className="px-6 py-3 border rounded-lg">تأكيد موافقة المشتري</button>}</div></div></div>
}
