'use client';
import { useEffect,useState } from 'react';
import { ArrowRight, Gavel, Search } from 'lucide-react';
export default function Auctions(){
 const [items,setItems]=useState<any[]>([]); const [make,setMake]=useState(''); const [model,setModel]=useState(''); const [year,setYear]=useState(''); const [bid,setBid]=useState<Record<string,string>>({});
 async function load(){const q=new URLSearchParams();if(make)q.set('make',make);if(model)q.set('model',model);if(year)q.set('year',year);const r=await fetch('/api/auctions?'+q);const x=await r.json();if(x.ok)setItems(x.auctions||[])}
 useEffect(()=>{load()},[make,model,year]);
 async function place(a:any){const amount=Number(bid[a.id]);if(!amount)return;const r=await fetch(`/api/auctions/${a.id}/bids`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({amount})});const x=await r.json();if(!x.ok)alert(x.error==='MINIMUM_BID_NOT_MET'?`الحد الأدنى للمزايدة: ${Number(x.minimum).toLocaleString('ar-YE')} ريال`:x.error||'تعذر تنفيذ المزايدة');else{setBid({...bid,[a.id]:''});load()}}
 return <main dir="rtl" className="min-h-screen bg-slate-50"><div className="mx-auto max-w-5xl p-4 md:p-7">
  <div className="mb-6 flex items-center justify-between"><a href="/" className="flex items-center gap-2 text-sm font-bold text-primary-900"><ArrowRight/>الرئيسية</a><h1 className="text-2xl font-black">المزادات</h1></div>
  <div className="mb-5 grid gap-2 rounded-2xl border bg-white p-4 md:grid-cols-3"><input value={make} onChange={e=>setMake(e.target.value)} placeholder="الماركة" className="rounded-xl border p-3"/><input value={model} onChange={e=>setModel(e.target.value)} placeholder="الموديل" className="rounded-xl border p-3"/><input value={year} onChange={e=>setYear(e.target.value)} placeholder="السنة" inputMode="numeric" className="rounded-xl border p-3"/></div>
  <p className="mb-4 flex items-center gap-2 text-sm text-slate-500"><Search size={17}/> الفلترة مرتبطة ببيانات المركبة: الماركة ← الموديل ← السنة، وليست بعنوان الإعلان.</p>
  <div className="grid gap-4 md:grid-cols-2">{items.map(a=><article key={a.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex justify-between"><div><h2 className="text-xl font-black">{a.vehicle.make} {a.vehicle.model}</h2><p className="text-sm text-slate-500">{a.vehicle.year} · {a.vehicle.city}</p></div><Gavel className="text-primary-900"/></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-slate-50 p-3">الحالي<br/><b>{Number(a.currentPrice).toLocaleString('ar-YE')} ريال</b></div><div className="rounded-xl bg-slate-50 p-3">ينتهي<br/><b>{new Date(a.endAt).toLocaleString('ar-YE')}</b></div></div><div className="mt-4 flex gap-2"><input value={bid[a.id]||''} onChange={e=>setBid({...bid,[a.id]:e.target.value})} placeholder={`أقل من ${Number(a.currentPrice)+Number(a.minimumIncrement)} غير مقبول`} inputMode="numeric" className="min-w-0 flex-1 rounded-xl border p-3"/><button onClick={()=>place(a)} className="rounded-xl bg-primary-900 px-4 font-bold text-white">زايد</button></div></article>)}{items.length===0&&<div className="rounded-2xl border bg-white p-8 text-center text-slate-500 md:col-span-2">لا توجد مزادات مطابقة حالياً.</div>}</div>
  <div className="mt-5 rounded-2xl border bg-amber-50 p-4 text-sm leading-7">الحد الأدنى للمزاد 50,000 ريال يمني. عند وصول مزايدة خلال آخر دقيقتين تمتد نهاية المزاد دقيقتين تلقائياً لمنع الحسم المفاجئ.</div>
 </div></main>
}
